import assert from 'node:assert/strict';
import { addDays, calendarRange, calendarReportDraft, canManageCalendar, daysInRange, calendarDefaultWorker, calendarProjectTitle, calendarProjectColor } from '../src/services/workCalendar';
import type { CalendarOccurrence } from '../src/services/workCalendar';
import { allTranslations } from '../src/i18n';
import fs from 'node:fs';
import ts from 'typescript';
assert.deepEqual(calendarRange('2026-10-11','week'),{from:'2026-10-05',to:'2026-10-11'});
assert.deepEqual(calendarRange('2026-10-11','month'),{from:'2026-09-28',to:'2026-11-01'});
assert.equal(daysInRange('2026-09-28','2026-11-01').length,35);
assert.equal(addDays('2026-10-25',1),'2026-10-26');
assert.equal(addDays('2026-03-29',-1),'2026-03-28');
assert.deepEqual(calendarRange('2026-12-31','upcoming'),{from:'2026-12-31',to:'2027-01-13'});
assert.equal(canManageCalendar({role:'operator'}),false);
assert.equal(canManageCalendar({role:'supervisor'}),true);
const o: CalendarOccurrence={scheduleId:'s',date:'2026-10-07',projectId:'p',projectName:'Alfa',clientId:'c',clientName:'Client',address:'Site',title:'Cleaning',notes:'Door',startTime:'18:00',endTime:'20:00',status:'planned',scheduleType:'recurring',exceptionId:null,workers:[{id:'dogan',name:'Dogan'}],reports:[]};
const draft=calendarReportDraft(o,'dogan');
assert.equal(draft.date,o.date);assert.equal(draft.projectId,o.projectId);assert.equal(draft.scheduleId,o.scheduleId);
assert.equal(draft.startTime,'18:00');assert.equal(draft.endTime,'20:00');assert.equal(draft.manualTotalHours,undefined);
assert.throws(()=>calendarReportDraft(o,'marco'));
assert.throws(()=>calendarReportDraft({...o,status:'cancelled'},'dogan'));
for(const language of Object.values(allTranslations)) assert.deepEqual(Object.keys(language.calendar).sort(),Object.keys(allTranslations.it.calendar).sort());
// Exercise the real report persistence/mapping, mocking only the Supabase I/O.
const exports: any = {};
let inserted: any;
const supabase={from(table:string) {assert.equal(table,'reports');return {insert(rows:any[]) {inserted=rows[0];return {select:async()=>({data:[{...inserted,id:'r'}],error:null})};}};}};
const compiled=ts.transpileModule(fs.readFileSync('src/services/dbService.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
new Function('exports','require',compiled)(exports,(name:string)=>name==='./supabase'?{supabase}:{});
const db=exports.db;db.setCompanyId('company');
const saved=await db.addReport({...draft,startTime:'18:00',endTime:'21:00'});
assert.equal(inserted.total_hours,3);assert.equal(inserted.schedule_id,'s');assert.equal(inserted.schedule_date,o.date);
assert.equal(saved.scheduleId,'s');assert.equal(saved.scheduleDate,o.date);assert.equal(saved.totalHours,3);
const {scheduleId,scheduleDate,...manual}=draft;
await db.addReport({...manual,startTime:'08:00',endTime:'12:00'});
assert.equal(Object.hasOwn(inserted,'schedule_id'),false);assert.equal(Object.hasOwn(inserted,'schedule_date'),false);assert.equal(inserted.total_hours,4);
console.log('PASS: calendar dates/DST, bounded ranges, real report persistence/mapping, actual hours independent of plan, manual reports unchanged, worker validation, six-language parity.');

assert.equal(calendarDefaultWorker(o,'dogan'),'dogan');
assert.equal(calendarDefaultWorker(o,'manager'),'');
assert.equal(calendarProjectTitle({name:'Project',description:' Activity '}),'Activity');
assert.equal(calendarProjectTitle({name:'Project',description:''}),'Project');
assert.equal(calendarProjectTitle({name:'Project',description:'x'.repeat(250)}).length,200);
assert.deepEqual(calendarProjectColor('p'),calendarProjectColor('p'));
assert.notDeepEqual(calendarProjectColor('p'),calendarProjectColor('q'));
const team={...o,workers:[...o.workers,{id:'marco',name:'Marco'},{id:'anna',name:'Anna'}],reports:[{id:'existing',workerId:'anna'}]};
const teamDraft=calendarReportDraft(team,'dogan');
assert.deepEqual(teamDraft.additionalWorkers.map(w=>w.userId),['marco']);
assert.equal(teamDraft.additionalWorkers[0].startTime,'18:00');
assert.equal(teamDraft.additionalWorkers[0].endTime,'20:00');
assert.equal(calendarReportDraft({...o,startTime:null,endTime:null},'dogan').startTime,'');
